# Generated by Django 6.0.2 on 2026-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
